import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "playwright-report/**",
      "test-results/**",
      // generated by Next.js
      "next-env.d.ts",
    ],
  },
  {
    rules: {
      // The service-role client and WebRTC glue legitimately deal in unknowns;
      // we still forbid implicit/unexplained any.
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
];

export default config;
